version: '2'

networks:
  etcd-net:

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.3.18
    container_name: etcd1
    restart: always
    command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "2379:2379"
    volumes:
      - d:/dockershare/etcd/etcd1:/etcd-dataaa
    networks:
      - etcd-net

  etcd2:
    image: quay.io/coreos/etcd:v3.3.18
    container_name: etcd2
    restart: always
    command: etcd -name etcd2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "2479:2379"
    volumes:
      - d:/dockershare/etcd/etcd2:/etcd-data
    networks:
      - etcd-net

  etcd3:
    image: quay.io/coreos/etcd:v3.3.18
    container_name: etcd3
    restart: always
    command: etcd -name etcd3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    ports:
      - "2579:2379"
    volumes:
      - d:/dockershare/etcd/etcd3:/etcd-data
    networks:
      - etcd-net